name: Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.ALPHACURL_SSH_KEY }}"
        pip install -r requirements.txt
        python -m pip install pytest pytest-timeout
    - name: Test with pytest (pull request)
      if: github.event_name == 'pull_request'
      run: pytest tests/ --timeout 30 -m "not slow and not display"
    - name: Test with pytest (master push)
      if: github.event_name == 'push'
      run: pytest tests/ --timeout 30 -m "not slow and not display and not flaky"
